models:
  - name: customers_stg
    description: Staged customer data from order management system (OMS), with minor row-level transformations.
    columns:
      - name: email
        tests:
          - string_not_empty

  - name: employees_stg
    description: Staged employees data from order management system (oms), with minor row-level transformations.
    columns:
      - name: jobtitle
        tests:
          - string_not_empty

  - name: orders_stg
    description: Staged orders data from order management system (oms), with minor row-level transformations.
    columns:
      - name: orderid
        tests:
          - unique
          - not_null

      - name: statusdesc
        description: "{{ doc('statusdesc') }}"
        tests:
          - accepted_values:
              arguments:
                values: ['01', '02', '03']

  - name: orderitems_stg
    description: Staged order items data from order management system (oms), with minor row-level transformations.
    columns:
      - name: orderid
        tests:
          - relationships:
              arguments:
                to: ref('orders_stg')
                field: orderid