models:
  - name: customers_stg
    columns:
      - name: email
        tests:
          - string_not_empty

  - name: employees_stg
    columns:
      - name: jobtitle
        tests:
          - string_not_empty

  - name: orders_stg
    columns:
      - name: orderid
        tests:
          - unique
          - not_null

      - name: statusdesc
        tests:
          - accepted_values:
              arguments:
                values: ['01', '02', '03']

  - name: orderitems_stg
    columns:
      - name: orderid
        tests:
          - relationships:
              arguments:
                to: ref('orders_stg')
                field: orderid